import { Project, Skill, Experience } from './types';
import { FaFigma } from "react-icons/fa";
import { FiFramer } from "react-icons/fi";
import { FaReact } from "react-icons/fa";
import { AiOutlinePython } from "react-icons/ai";
import { TbBrandTypescript } from "react-icons/tb";
import { VscServerProcess } from "react-icons/vsc";
import { IoChatboxEllipsesOutline } from "react-icons/io5";
import { SiJavascript } from "react-icons/si";
import { FaJava } from "react-icons/fa";
import { SiCplusplus, SiC, SiHtml5, SiCss, SiTailwindcss, SiSqlite, SiNodedotjs, SiExpress, SiMongodb } from "react-icons/si";

import bontempsImage from "/bontempsWebsite.jpg";
import sgbImage from "/sgbWebsite.png";
import moviesBuffImage from "/moviesbuffWebsite.png";
import weatherCheckImage from "/weathercheckWebsite.png";
import systemSignupImage from "/systemsignupWebsite.jpg";

export const PROJECTS: Project[] = [
  {
    id: 'bontemps',
    title: 'Bontemps',
    description: 'Building a high-performance Ecommerce Pastry Website.',
    category: 'Pastry Ecommerce',
    image: bontempsImage,
    url: 'https://bontemps.in',
  },
  {
    id: 'SGB',
    title: 'Southern Gourmet Bites',
    description: 'SGB is a chocolate company, it produce high quality bean to bar chocolates',
    category: 'Brand Website',
    image: sgbImage,
    url: 'https://southerngourmetbites.com',
  },
  {
    id: 'movies-buff',
    title: 'Movies Buff',
    description: 'Movies website for movies lover it have the features like search, details, add to watchlist',
    category: 'Website',
    image: moviesBuffImage,
    url: 'https://iamjagadeesan.github.io/MoviesBuff/#/',
  },
  {
    id: 'weather-check',
    title: 'Weather Check',
    description: 'Weather app to check the current climate in any location.',
    category: 'Website',
    image: weatherCheckImage,
    url: 'https://iamjagadeesan.github.io/Weathercheck/',
  },
  {
    id: 'system-signup',
    title: 'System Signup',
    description: 'system login and signup on terminal using C programming.',
    category: 'system signup',
    image: systemSignupImage,
    url: 'https://github.com/iamjagadeesan/C_Projects/tree/main/System%20Login%20Project',
  },
];

export const SKILLS: Skill[] = [
  {
    id: 'figma',
    name: 'Figma',
    description: 'UI/UX Design & Prototyping',
    category: 'Design',
    icon: FaFigma,
    rating: 5,
    status: 'GET',
    color: '#FF7262',
  },
  {
    id: 'framer',
    name: 'Framer',
    description: 'Interaction & Web Design',
    category: 'Design',
    icon: FiFramer ,
    rating: 3,
    status: 'GET',
    color: '#0055FF',
  },
  {
    id: 'react',
    name: 'React',
    description: 'Hooks, Context & Redux',
    category: 'Development',
    icon: FaReact,
    rating: 5,
    status: 'OPEN',
    color: '#61DAFB',
  },
  {
    id: 'python',
    name: 'Python',
    description: 'Data Science & Flask',
    category: 'Development',
    icon: AiOutlinePython,
    rating: 4,
    status: 'OPEN',
    color: '#FFD43B',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    description: 'Strict Typing & Interfaces',
    category: 'Development',
    icon: TbBrandTypescript,
    rating: 4,
    status: 'OPEN',
    color: '#3178C6',
  },
  {
    id: 'agile',
    name: 'Agile Management',
    description: 'Scrum, Kanban & Team Leadership',
    category: 'Soft Skills',
    icon: VscServerProcess,
    rating: 5,
    status: 'VIEW',
    color: '#FF5F56',
  },
  {
    id: 'writing',
    name: 'Technical Writing',
    description: 'Documentation & Presentations',
    category: 'Soft Skills',
    icon: IoChatboxEllipsesOutline,
    rating: 4,
    status: 'VIEW',
    color: '#4B8EFF',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    description: 'ES6+, DOM & Async Programming',
    category: 'Development',
    icon: SiJavascript,
    rating: 5,
    status: 'OPEN',
    color: '#F7DF1E',
  },
  {
    id: 'java',
    name: 'Java',
    description: 'OOP, Spring & Backend Development',
    category: 'Development',
    icon: FaJava,
    rating: 3,
    status: 'OPEN',
    color: '#007396',
  },
  {
    id: 'cpp',
    name: 'C++',
    description: 'Object-Oriented & Systems Programming',
    category: 'Development',
    icon: SiCplusplus,
    rating: 3,
    status: 'OPEN',
    color: '#00599C',
  },
  {
    id: 'c',
    name: 'C',
    description: 'Procedural Programming & Data Structures',
    category: 'Development',
    icon: SiC,
    rating: 4,
    status: 'OPEN',
    color: '#A8B9CC',
  },
  {
    id: 'html',
    name: 'HTML',
    description: 'Semantic Markup & Web Structure',
    category: 'Development',
    icon: SiHtml5,
    rating: 5,
    status: 'OPEN',
    color: '#E34C26',
  },
  {
    id: 'css',
    name: 'CSS',
    description: 'Styling, Flexbox & Grid Layouts',
    category: 'Development',
    icon: SiCss,
    rating: 5,
    status: 'OPEN',
    color: '#1572B6',
  },
  {
    id: 'tailwindcss',
    name: 'Tailwind CSS',
    description: 'Utility-First CSS Framework',
    category: 'Development',
    icon: SiTailwindcss,
    rating: 5,
    status: 'OPEN',
    color: '#06B6D4',
  },
  {
    id: 'sql',
    name: 'SQL',
    description: 'Database Queries & Optimization',
    category: 'Development',
    icon: SiSqlite,
    rating: 4,
    status: 'OPEN',
    color: '#003B57',
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'JavaScript Runtime & Backend',
    category: 'Development',
    icon: SiNodedotjs,
    rating: 5,
    status: 'OPEN',
    color: '#68A063',
  },
  {
    id: 'expressjs',
    name: 'Express.js',
    description: 'Web Framework & REST APIs',
    category: 'Development',
    icon: SiExpress,
    rating: 5,
    status: 'OPEN',
    color: '#000000',
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: 'NoSQL Database & Document Model',
    category: 'Development',
    icon: SiMongodb,
    rating: 5,
    status: 'OPEN',
    color: '#13AA52',
  },
];

export const EXPERIENCE: Experience[] = [
  {
    id: 'sgb',
    role: 'Full Stack developer',
    company: 'Southern Gourmet Bites',
    period: '2025 — Present',
    description: 'Led design for M4 architecture tools. Mentored a team of 4 junior designers.',
    current: true,
    tags: ['UI Design', 'Redux'],
  },
  {
    id: '',
    role: 'MERN Stack Intern',
    company: 'Tripple One Solutions',
    period: 'June 2025 — 2025',
    description: 'Focused on developing design systems for high-fidelity fintech applications.',
    tags: ['Frontend', 'Backend'],
  },
  {
    id: 'dataScience',
    role: 'Data Science Intern',
    company: 'SHIASH solutions pvt limited, chennai',
    period: 'May 2023 — August 2023',
    description: 'Learned machine learning technics, deep learning process, AI infrastructure',
    tags: ['Machine Learning', 'Deep Learning', 'Artificial Intelligence'],
  },
];
